### ISSUE TITLE
Change of formatting in filename for downloadable releases

### ISSUE THREAD

**Issue by Cheaternl** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#25]
During the livestream of Superhouse (timestamped: https://youtu.be/QIPQd1B7gzg?t=1972) it appeared that Jonathan downloaded a firmware release which has no version indication. Leaving him clueless what version that could be (which could lead to frustration if you would have uploaded an old version...)

I think that screams for an improvement in the filename strategy. 
As far as I can lookup for other (non-Superhouse) github repo's, they all give you downloadable assets for each release, with a version number in the filename.

Enhancement proposal:  Add version number in filename for each downloadable firmware in Github.

**Comment by austinscreations** [comment]
while the filename could be changed - it's a decision i'll leave for @sumnerboy12
the version is hardcoded into the firmware itself and can be accessed via the webUI and json adopt payloads. it also shows on the LCD of the rack and shows on serial debug

**Comment by sumnerboy12** [comment]
Totally agree @Cheaternl. What would be great would be to setup some Github actions to automatically compile the firmware whenever a new `x.y.z` tag is pushed, and create a new release. That process could handle the naming of the binary to ensure it included the version number.

I am hoping someone (maybe you?) could take up this batten as I am struggling to find the time currently.

**Comment by jonoxer** [comment]
This is an excellent suggestion @Cheaternl. I have the same problem with Tasmota, so I've got into the habit of renaming the binaries after I download them.

Renaming the generated binary before committing the release is a manual solution but @sumnerboy12's suggestion of automating compilation and renaming would be nicer. The problem is finding someone with the time to set it up.
