### ISSUE TITLE
spelling of compiler flag WIFIMODE not consistant

### ISSUE THREAD

**Issue by moinmoin-sh** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#36]
Compiler flag to enable WiFi have different spelling:

RACK32       : `WIFIMODE`
ROOM8266 : `WIFI_MODE`

The `platformio.ini` doesn't take care for it.

Should be the same spelling for consistancy and required if used FW wide in common modules.

**Comment by sumnerboy12** [comment]
@austincreations - you introduced this flag - what would you prefer going forward?

**Comment by moinmoin-sh** [comment]
Looks like I've to apologize!
I checked again today and found out that `WIFI_MODE` is spelled the same in RACK32 and ROOM8266.

It's the `platformio.ini` where the typo crept in.  `WIFIMODE `has to be replaced with `WIFI_MODE`.
(perhabs copied from here https://github.com/sumnerboy12/OXRS-BJ-FlowSensor-ESP-FW/blob/main/platformio.ini ?)

Please double check. Sorry for the confusion.
