### ISSUE TITLE
Add command to query "all" input state

### ISSUE THREAD

**Issue by sumnerboy12** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#41]
Useful for a home automation platform/system to initialise its own state on startup. Fire off a "query all" command and it will get back the current state of all inputs.

Have to be careful that this doesn't trigger automations or rules tho. Should these state updates be published to a different topic, rather than the standard `stat/<deviceid>`?

**Comment by moinmoin-sh** [comment]
Wouldn't be this a good use case for the `retain `flag ? Itcould be made configurable to select if messages should have the `retain `flag.
That would only make sense for those types that have a state like `switch `, `contact `, `security `.

**Comment by sumnerboy12** [comment]
That is a great idea Moin - I think that solves the problem. Would just need the ability to set this as a config parameter.

**Comment by sumnerboy12** [comment]
Most of the logic has been implemented in https://github.com/OXRS-IO/OXRS-IO-IOHandler-ESP32-LIB/pull/5

**Comment by sumnerboy12** [comment]
Implemented by #44
