### ISSUE TITLE
Add configurable option for publishing "retained" state messages

### ISSUE THREAD

**Issue by sumnerboy12** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#42]
Relates to #41.

Could start with a global option, so on/off for all inputs. If required it could be made per-input.

Would need a change to the MQTT library, to allow passing the retained flag to `publishStatus()`.

Would only make sense for `switch`, `security` or `contact` inputs.

**Comment by moinmoin-sh** [comment]
Could also be usefull to publish the actul state of the retained inputs at start-up to make sure everything is in sync.

**Comment by sumnerboy12** [comment]
Yes, also a good idea, but probably should be optional - again, global on/off to start with and then move to a per/input setting if needed later?

**Comment by moinmoin-sh** [comment]
Yes, global option on/off for retained messages. Config per-input only if there is a demand.

I see` publish on start-up` as madatory if retained is tuned on.
This could be a little tricky for inputs that change state after configured. Possibly start-up states should  only be published for configured inputs after a config payload is received.

When writing this, it comes to my mind that it's not possible to send retained messages for individual inputs because the retained messages are handled by the topic and we have a single topic for all inputs.

**Comment by sumnerboy12** [comment]
Yes of course, you are right. We can't support retained `stat/` messages with our current topic/payload format. I think a simple `queryAll` command is probably the easiest solution (original idea). This makes it an optional step, which could be triggered when you receive `stat/xxx/lwt -> { "online": true }` to achieve "publish on startup".

Otherwise it can be periodically triggered to ensure your logic system is kept in sync.

**Comment by moinmoin-sh** [comment]
It's a shame that we can't support retained stat/ messages, would have been smart to use.
I should have known better before making suggestions. Sorry for the confusion.

Your backend initiated query solution seems to be the right pass forward.

**Comment by sumnerboy12** [comment]
I should have realized also, it was a good idea tho. We could look at adding index specific topics along with the standard one, if we thought it was really worth while. 

I'll have a look at adding this feature and get you to review in the next few days.

**Comment by austinscreations** [comment]
i feel like `query/<deviceID>` could be the way to go. i like `query` more than `queryAll` as within the payload it could give the option to query all or just a singular state on a device. which depending on someone's choice of setting up NR flows can make payloads potentially more manageable.

**Comment by sumnerboy12** [comment]
I would prefer not to add another root level topic. We have stat/, conf/, cmnd/ and tele/ already. This seems like it belongs under cmnd/ given you are instructing it to do something.

**Comment by austinscreations** [comment]
Ah, ok. My apologies I thought that was what was going to end up being created. But if it's just a payload then all good. And yes `cmnd` makes sense

**Comment by sumnerboy12** [comment]
Yeah so you would publish the `queryAll` command and we would then publish the state of every input to stat/ as normal.

So anything listening doesn't have to worry about two end points etc.

**Comment by sumnerboy12** [comment]
Closing as without changing out topic structure (to have a unique topic per input) we can't use `retain` to persist the current input state.
